apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ml
  annotations:
    serving.kserve.io/s3-endpoint: s3.ap-south-1.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: ap-south-1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: AKIAUA7R5LXIEERCVY4Z
  AWS_SECRET_ACCESS_KEY: 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
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: ml
secrets:
- name: s3-secret
